version: '3.8'
services:
  my_hugtranformer_service:
    image: gpu-and-tranformers-img
    command: ["--gpus", "all"]
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./pytorch-huggingface-tutorial:/code
    environment:
      - "ENV_VAR=value"
      - "NVIDIA_VISIBLE_DEVICES=all"
    ports:
      - "8000:8000"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      - "/dev/nvidia-caps:/dev/nvidia-caps"
